- platforms/msx2/.gitignore
- platforms/msx2/Makefile
- platforms/msx2/crt0.z80
- platforms/msx2/input.c
- platforms/msx2/input.h
- platforms/msx2/video.c
> [MSX] build system

- common/main.c
- common/minefield.c
- common/minefield.h
- platforms/ncurses/input.c
- platforms/ncurses/video.c
- Also accept spacebar for opening cells.
- And fixed code indentation using tabs.
> [ncurses] handle up & down keys

- common/input.h
- common/main.c
- common/minefield.c
- common/minefield.h
- platforms/ncurses/input.c
- platforms/ncurses/video.c
Removed that infinite loop so that the shutdown function is called when the player decided to quit the game. We'll at some point also implement a title screen, a game over message, and perhaps a prompt for name entry and a list of highest records (how quickly a player took to clear a minefield).
> restructure the code and add a QUIT key

- README.md
- common/input.h
- platforms/msx2/input.c
Using Xorshift random number generator.
> [MSX] random_number() implemented

- common/main.c
- common/main.h
- platforms/gunsmoke/video.c
There's partial support for drawing sprites, but it is not actually used.
> [gunsmoke] highlight current cell and add some helper graphics functions.

- platforms/gunsmoke/boot.s
- platforms/gunsmoke/input.c
- platforms/gunsmoke/video.c
And do so cleanly, not leaving artifacts on the screen during reboot.
This means I refactored some of the graphics routines here.
> [gunsmoke] Allow the game to reboot once user quits

- common/common.h
- common/main.c
- common/main.h
- common/minefield.c
- platforms/gunsmoke/input.c
- platforms/msx2/Makefile
- platforms/msx2/debug.h
- platforms/msx2/debugdevice.tcl
- platforms/msx2/input.c
- platforms/msx2/msx.h
- platforms/msx2/video.c
- platforms/msx2/xorshift.z80
- platforms/ncurses/input.c
This is based on openMSX' debugdevice.
> a common debugging interface

- common/main.c
- common/main.h
- platforms/gunsmoke/video.c
- platforms/msx2/video.c
- platforms/ncurses/video.c
> function to draw a single cell to improve performance on slower video systems.

- platforms/msx2/Makefile
- platforms/msx2/cursor.h
- platforms/msx2/msx2.h
- platforms/msx2/read_clock.asm
- platforms/msx2/video.c
And updating a dependency in the Makefile.
> [MSX] fixing generated code for SDCC 4.2.0

- .github/workflows/workflow-build.yaml
invalid package name contains backslash character. This also fixes #72
> [MSX] invalid char in string expansion

- .github/workflows/latest.yaml
- .github/workflows/workflow-build.yaml
This will use Github's action matrix to generate builds in parallel.
> generic github build action

- platforms/msdos/video.c
> [msdos] Direct VGA mem. writes improve performance

- common/main.c
- common/minefield.c
- common/minefield.h
> fix bug when opening blocks and counting bombs

- common/minefield.c
- common/video-tiles.c
This reduces the code size in the MS-DOS port by ~180 bytes.
> Reduce common code size

- platforms/ncurses/Makefile
- platforms/opengl/extras.c
> [opengl] `glutLeaveMainLoop()` used to exit game

- platforms/msx2/Makefile
- platforms/msx2/tools/Makefile
- platforms/msx2/tools/SCREEN5.c
using macro expansion to change xpm file and variable name.
> [msx] allow different file and variable names

- common/game.h
- common/main.c
- common/main.h
- common/minefield.c
- common/minefield.h
- common/video-tiles.c
- common/video-tiles.h
- platforms/fuzz/input.c
- platforms/gunsmoke/video.c
- platforms/msdos/.gitignore
- platforms/msdos/video.c
- platforms/msx2/Makefile
- platforms/msx2/video.c
- platforms/ncurses/video.c
- platforms/opengl/extras.c
- platforms/opengl/video.c
Also changed the way screen is updated by creating a `changed` boolean variable that only updates the screen if needed.
> leveraging some opengl functions to create a single game loop function

- common/common.h
- common/main.c
- common/minefield.c
- common/minefield.h
- common/video-tiles.h
- platforms/msdos/Makefile
- platforms/msdos/video.c
- platforms/msx2/msx2.h
- platforms/msx2/video.c
#91: generic game won status and msx2 implementation.
Draft mode because something broke after 0956cc65853c6c6c646b634bda56c8e2b015d5ab
> [msx2] implement game won status

- common/minefield.c
without this fix, user can win the game by just flagging all remaining cells.
> [common] forgetting case where cell has invalid flag

- common/common.h
- common/game.h
- common/main.c
- platforms/ncurses/input.c
- platforms/ncurses/video.c
...and there is a fps counter in the ncurses platform.
> [common][ncurses] `idle_update()` controls fps using `wait_tick()`

- common/main.c
- common/minefield.c
- common/video-tiles.c
- platforms/msdos/video.c
- platforms/msx2/video.c
- platforms/ncurses/video.c
- platforms/opengl/video.c
* `game_over()` function no longer necessary.
> [common] fixed multiple mine detonation

- platforms/psx/CMakeLists.txt
- platforms/psx/input.c
- platforms/psx/video.c
This PR:
- fixes isbg behavior (and now the background shows up) 
- fixed display() behavior
- adds a random number generator
- reimplements the main loop to better control display and clear ot behavior 
- cursor now shows up on real hw and is movable! 
TODO
> [psx] fixing isbg and other things - WIP

- platforms/msx2/mouse.c
- platforms/msx2/mouselib.asm
- platforms/msx2/msx2.h
- platforms/msx2/video.c
Displays/hides mouse automatically when it is plugged/unplugged.
> [msx2] autodetect mouse

- platforms/msx2/mouselib.asm
fix mouse behaviour when compiling with an old version of SDCC.
> [msx2] __sdcccall(0) calling convention fix

- common/common.h
- common/game.h
- platforms/msx2/debug.c
- platforms/msx2/debugdevice.tcl
- platforms/msx2/extras.c
- platforms/msx2/input.c
- platforms/msx2/read_keyboard_row.asm
- platforms/msx2/video.c
* moved some functions from **video.c** to **extras.c** (`idle_update`, `platform_init`, `platform_shutdown`);
* more lightweight debugging functions uses Tcl features on the emulator side;
* `debug` now accepts 16-bit integers;
* `keyboard_read_row` renamed to `read_keyboard_row`. Moved to own file;
> Improve debug
